apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yhjpo3zmi-java-springboot
  janus-idp.io/tekton: yhjpo3zmi-java-springboot
  backstage.io/kubernetes-id: yhjpo3zmi-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: yhjpo3zmi-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
